stages:
  data_cleaning:
    cmd: python src/data/data_ingestion.py
    deps:
    - data/raw/swiggy.csv
    - src/data/data_ingestion.py
    outs:
    - data/cleaned/swiggy_cleaned.csv

  data_preparation:
    cmd: python src/data/data_preparation.py
    params:
    - Data_Preparation.test_size
    - Data_Preparation.random_state
    deps:
    - data/cleaned/swiggy_cleaned.csv
    - src/data/data_preparation.py
    outs:
    - data/interim/train.csv
    - data/interim/test.csv
  data_preprocessing:
    cmd: python src/features/data_preprocessing.py
    deps:
    - data/interim/train.csv
    - data/interim/test.csv
    - src/features/data_preprocessing.py
    outs:
    - data/processed/train_trans.csv
    - data/processed/test_trans.csv
    - models/preprocessor.joblib
  model_training:
    cmd: python src/model/model_training.py
    deps:
    - src/model/model_training.py
    - data/processed/train_trans.csv
    params:
    - Train.Random_Forest
    - Train.LightGBM
    outs:
    - models/model.joblib
    - models/power_transformer.joblib
    - models/stacking_regressor.joblib
  model_evaluation:
    cmd: python src/model/model_evaluation.py
    deps:
    - src/model/model_evaluation.py
    - data/processed/train_trans.csv
    - data/processed/test_trans.csv
    - models/model.joblib
    outs:
    - run_information.json


